# Generated by Django 5.0.7 on 2024-10-07 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0002_addcourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddCourse',
        ),
    ]
