# Generated by Django 5.1 on 2024-11-13 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0003_feedback'),
        ('facultyapp', '0005_marks'),
    ]

    operations = [
    ]
