# Generated by Django 5.0.7 on 2024-09-26 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_user_studentlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
